---
version: '3'
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "${UMAMI_PORT:-3000}:3000"
    environment:
      DATABASE_URL: postgresql://umami:Sy970830..@hostctl-postgresql-11e035:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:${UMAMI_PORT:-3000}/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  umami-db-data:
